### PR TITLE
Validate hook

### PR DESCRIPTION
**Pull request by agentrickard**
Fixes the issue documented in https://www.drupal.org/node/2884470

### CODE REVIEW

**Comment by agentrickard** [comment]
I really don't understand these test fails.

**Comment by agentrickard** [comment]
Schema should be inherited. What the #!@$ changed in core?

**Comment by zerolab** [comment]
Could it be related to https://www.drupal.org/node/2870971 ?

**Comment by agentrickard** [comment]
Yup. That's it. I just couldn't find the change notice because this manifests as a schema error, and searching for 'schema' doesn't pull up this record.

**Pull request merged**
