### PR TITLE
220 fix

### PR DESCRIPTION
**Pull request by agentrickard**
Incorporates #220 into a new PR.

### CODE REVIEW

**Comment by agentrickard** [comment]
These tests all pass locally. WTF?

**Comment by zerolab** [comment]
I am not entirely sure.

Saying that, this is what I get on my OSX setup:

```
php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://localhost:8080 "domain,domain_access,domain_alias,domain_config,domain_source"

Drupal\domain\Tests\Condition\DomainConditionTest              9 passes
Drupal\domain\Tests\DomainCreateTest                          19 passes
Drupal\domain\Tests\DomainActionsTest                         25 passes                            3 messages
Drupal\domain\Tests\DomainHooksTest                            8 passes
Drupal\domain\Tests\DomainInactiveTest                        15 passes                            3 messages
Drupal\domain\Tests\DomainFormsTest                           40 passes                           12 messages
Drupal\domain\Tests\DomainEntityReferenceTest                 50 passes                           11 messages
Drupal\domain\Tests\DomainValidatorTest                        7 passes
Drupal\domain\Tests\DomainNegotiatorTest                      17 passes                            4 messages
Drupal\domain_access\Tests\DomainAccessFieldTest             171 passes   9 fails                 35 messages
Drupal\domain_access\Tests\DomainAccessAllAffiliatesTest      41 passes   4 fails                  9 messages
Drupal\domain_access\Tests\DomainAccessGrantsTest             41 passes                           10 messages
Drupal\domain_access\Tests\DomainAccessRecordsTest            22 passes
Drupal\domain_alias\Tests\DomainAliasNegotiatorTest           13 passes             1 exceptions   2 messages
Drupal\domain_access\Tests\DomainAccessEntityReferenceTest    53 passes   7 fails                 12 messages
Drupal\domain_config\Tests\DomainConfigHomepageTest           44 passes   9 fails                 15 messages
Drupal\domain_access\Tests\DomainAccessPermissionsTest       189 passes   4 fails                 44 messages
Drupal\domain_config\Tests\DomainConfigOverriderTest          57 passes                           17 messages
Drupal\domain_source\Tests\DomainSourceEntityReferenceTest    53 passes                           11 messages
Test run duration: 5 min 35 sec
```

I do have:

```
127.0.0.1 one.localhost two.localhost three.localhost four.localhost five.localhost
```

**Comment by agentrickard** [comment]
These are probably tests that use example_com explicitly, then.  On my local I use example.com, one.example.com, etc.

I thought I had wired the tests to always use example_com variants as the machine names. See DomainTestBase.

```
   * In my environment, I use the example.com hostname as a base. Then I name
   * hostnames one.* two.* up to ten. Note that we always use *_example_com
   * for the machine_name (entity id) value, though the hostname can vary
   * based on the system. This naming allows us to load test schema files.
```

**Comment by agentrickard** [comment]
See #234

**Comment by zerolab** [comment]
_very_ good catch. For the life of me I could not understand why this happening.

#234 is a good idea as I suspect the test runner on d.o. may have issues with custom domains.

**Pull request merged**
