### PR TITLE
Provide domain access config schema for views.

### PR DESCRIPTION
**Pull request by dpagini**
see https://www.drupal.org/project/domain/issues/2957999

### CODE REVIEW

**Comment by agentrickard** [comment]
IS this all that we're missing right now? I thought there was more?

**Comment by dpagini** [comment]
So I have a view that uses this access mechanism that is failing when I'm trying to run tests. I'm honestly not sure if there would be more to provide schemas for...

**Comment by agentrickard** [comment]
Use the config_inspector module.

**Comment by dpagini** [comment]
Yeah, I mean it's the only config that I'm using that's giving me a problem. I don't use the whole suite of modules, mostly just `domain` and `domain_access` I believe. I wouldn't have even seen the views issue unless I had a view that used domain to limit access, you know?

**Pull request merged**
