### PR TITLE
Fix for field access checking.

### PR DESCRIPTION
**Pull request by agentrickard**
See #337

### CODE REVIEW

**Comment by agentrickard** [comment]
@andypost This should fix the issue. I used AccountInterface because there may be cases where that is implemented, and UserInterface inherits from it.

**Comment by andypost** [comment]
Looks great to me! Travis needs kinda `echo "sendmail_path=/bin/true" >> /etc/php7/conf.d/xx-mail.ini`

**Comment by zerolab** [comment]
Thanks for the suggestion @andypost, that is kind there, in a slightly different form -- https://github.com/agentrickard/domain/blob/8.x-1.x/.travis.yml#L72

**Comment by andypost** [comment]
@zerolab thanx, then it very strange that tests fail on site install

**Comment by agentrickard** [comment]
That might just be a Travis bug. It passed in all other contexts. Retesting.

**Comment by agentrickard** [comment]
Test passed on retry and all tests pass locally.

**Pull request merged**
