### PR TITLE
Try to fix the field install of the admin field.

### PR DESCRIPTION
**Pull request by agentrickard**
Let's run the testbot on this. (See #311

### CODE REVIEW

**Comment by agentrickard** [comment]
This really needs a test of the user/register form.

**Comment by andypost** [comment]
I think better to change field storage in domain_access `persist_with_no_fields: true` and add `enforce` dependency to make them uninstallable automatically when doamin-access uninstalled

**Comment by agentrickard** [comment]
That's a separate issue. This issue is that the wrong EntityReferneceSelect plugin was being assigned to the domain_admin field.

**Comment by agentrickard** [comment]
Added another test to ensure that edit and admin fields are handled differently. This should be ready to go once it passes.

We'll then update the field definition as part of #310

**Pull request merged**
