### PR TITLE
Delete the Domain Alpha module. Requires a cache rebuild.

### PR DESCRIPTION
**Pull request by agentrickard**
See https://www.drupal.org/project/domain/issues/2960228

### CODE REVIEW

**Comment by rivimey** [comment]
@agentrickard perhaps this would be a good time to action this PR?

**Comment by agentrickard** [comment]
Yes, before the beta, at the least. My concern is that it requires people to uninstall the module before it can be deleted.

**Comment by zerolab** [comment]
I think that should be an upgrade consideration in the release notes.

Unless you want to add a `hook_update_n` implementation in one release, then actually remove the module in a followup one..

```php
/**
 * Uninstall Domain Alpha, if installed.
 */
function domain_update_8002() {
  \Drupal::service('module_installer')->uninstall(['domain_alpha']);
}
```

**Comment by agentrickard** [comment]
I was just going to add it in the release notes, because even an uninstall like this won't stop people from re-enabling it.

The problem is that few people read release notes.

**Comment by agentrickard** [comment]
That said, the next release is also going to require Drupal 8.5+, so reading the notes is pretty imperative.

**Comment by zerolab** [comment]
> The problem is that few people read release notes.

Heh, true. But you cannot account for everyone. And given the module is in alpha, things can still break. I think adding the release notes will be enough. And for the inevitable handful of people that don't bother to read the upgrade notes, well.. you did your best :)

**Comment by rivimey** [comment]
See also https://www.drupal.org/project/domain/issues/2960228

**Pull request merged**
