### PR TITLE
125 token

### PR DESCRIPTION
**Pull request by agentrickard**
Adds and tests tokens,

### CODE REVIEW

**Comment by agentrickard** [comment]
@zerolab any idea why these tests would fail on Travis? They seem to be fine locally.

**Comment by agentrickard** [comment]
This is deprecated for #271, which did get a little greedy.

**Comment by zerolab** [comment]
It is not directly obvious why they fail. Will have a look and hopefully have an answer in the next 1-2 days

**Comment by agentrickard** [comment]
Thanks. I assume it's to do with the port 8000. I actually don't know how that gets handled by the tokens.

I suspect that Token API strips out the colon from the hostname so that example.com:8000 tokenizes to example.com8000.

Note that this code is now in #271.

**Pull request closed without merging**
