### PR TITLE
Use config instead of hook_uninstall()

### PR DESCRIPTION
**Pull request by andypost**
This is a follow-up to https://www.drupal.org/node/2848014#comment-11917448

Fields are (un)installed from shipped config that makes hooks obsolete

### CODE REVIEW

**Comment by andypost** [comment]
Somehow tests are failed, ref #321

**Comment by andypost** [comment]
tests fail because field is not added to user form display
```
-    entity_get_form_display($entity_type, $bundle, 'default')
 -      ->setComponent(DOMAIN_ADMIN_FIELD, array(
 -        'type' => 'options_buttons',
 -        'weight' => 50,
 -      ))
 -      ->save();
```

**Comment by andypost** [comment]
Now uninstall tells what will be uninstalled

config-uninstall

**Comment by agentrickard** [comment]
Two questions:

1) Is this testable, or can we consider it covered by core tests?

2) How does this affect (or not) the need for dynamic field creation for nodes?

**Comment by andypost** [comment]
1) config dependencies have good testing coverage in core, that's why I suggest to rely on them, see http://cgit.drupalcode.org/drupal/tree/core/modules/config/src/Tests/ConfigOtherModuleTest.php as example for dependency on modules
2) dynamic field creation is not affected because fields depends on their storage that now have enforced dependencies on modules that provides them

basically when module will be uninstalled all dependent field storages will cause fields to be deleted - that's what I trying to show with screenshot

**Comment by agentrickard** [comment]
Got it. This is great.

I don't expect that these changes would apply to anyone who has installed the alpha versions of the module, would they?

I don't think we need to provide an update for that, though, since it should be clear what people need to do.

**Comment by andypost** [comment]
there's `domain_update_8001` already so it's easy to add update hooks
but I think no reason for alpha stage

**Comment by agentrickard** [comment]
I agree. Thanks again for this. Since tests pass, I'm going to commit and cleanup if necessary.

**Pull request merged**
