### PR TITLE
Handle cases where the entity is not passed in via $options.

### PR DESCRIPTION
**Pull request by agentrickard**
See #259

### CODE REVIEW

**Comment by agentrickard** [comment]
Needs tests.

**Comment by agentrickard** [comment]
The failure here is troubling. 

```
Pass      Browser    DomainSourceEntit  104 Drupal\domain_source\Tests\DomainSo

    Valid HTML found on "http://example.com:8080/node/add/article"

Exception User error RedirectResponseS   85 Drupal\Core\EventSubscriber\Redirec

    Redirects to external URLs are not allowed by default, use

    \Drupal\Core\Routing\TrustedRedirectResponse for it.

Pass      Browser    DomainSourceEntit  104 Drupal\domain_source\Tests\DomainSo

    POST http://example.com:8080/node/add/article returned 400 (111 bytes).

Fail      Browser    DomainSourceEntit  105 Drupal\domain_source\Tests\DomainSo

    HTTP response expected 200, actual 400
```

This suggests that the form save issued a redirect (because of the path rewrite) which was rejected by Drupal core. This redirect happens at the PathProcessorOutbound level, not the form level, so it may not be something we can account for.

I have not seen this issue when testing manually.

**Comment by agentrickard** [comment]
I take that back, I do see the issue when testing manually. Drupal's form system will not allow a redirect to an 'external' URL. The recommended solution to this, TrustedRedirectResponse, appears to be incompatible with FormState::setRedirect(). 

So we either have to ignore redirects on form submit (easy), figure out how to fix this issue (hard), or issue redirects at the page-load level if someone goes to a non-canonical URL for a node. 

I am hesitant to do that last one, but it might be the best option.

**Comment by zerolab** [comment]
https://www.drupal.org/node/2599342 claims you can do `$form_state->setResponse(new TrustedRedirectResponse());`

**Comment by agentrickard** [comment]
FFS. What yched is saying is that you have to use setResponse(), not setRedirect(), which is a total WTF,

Thanks!

**Comment by agentrickard** [comment]
Ok, this should fix up that issue nicely, then.

**Comment by agentrickard** [comment]
This looks good, but still needs a test of menu links / local tabs.

**Comment by agentrickard** [comment]
Should be all set now.

**Pull request merged**
