### PR TITLE
Condition form

### PR DESCRIPTION
**Pull request by agentrickard**
Builds on work from #455 and sets the form element to something readable.

screen shot 2018-11-14 at 1 26 30 pm

### CODE REVIEW

**Comment by dpagini** [comment]
Just FYI - I pulled this patch into my project that was having the issues, and can confirm it does fix my problem.

**Comment by agentrickard** [comment]
Thanks.

**Comment by agentrickard** [comment]
See https://www.drupal.org/project/domain/issues/3011055

**Comment by jcmartinez** [comment]
Patching with composer from this PR against 1.0.0-alpha14 didn't apply for me. I had to patch from 455.

**Comment by dpagini** [comment]
Same for me @jcmartinez. I think this ended up with a rogue extra commit on it, so I went back to that other PR.

**Comment by agentrickard** [comment]
That's probably due to the merge conflict noted in 21ffdee

**Pull request merged**
