### PR TITLE
Migrate files for Domain records D7 -> D8

### PR DESCRIPTION
**Pull request by enzolutions**
This PR contains a migration template and source to enable migrate from Drupal 7 to Drupal 8 domain records.

### CODE REVIEW

**Comment by agentrickard** [comment]
Sorry. I didn't see this until today.

**Comment by agentrickard** [comment]
I haven't touched Migrate in D8 yet. What else do we need? Is this testable?

**Comment by enzolutions** [comment]
If you asked about if there unit test or test unit, nope

**Comment by agentrickard** [comment]
I'm suggesting that we write a test. There are examples in the migrate_drupal module.

**Comment by enzolutions** [comment]
I will request to my team to do that in couple weeks

**Comment by agentrickard** [comment]
I am assuming that this Pull Request is not a blocker for the team?

**Comment by enzolutions** [comment]
Nope, almost everything works, we just write that to migrate configuration from D7 to D8 and works. Now we are dealing with other d8 stuffs not related with domain

**Comment by agentrickard** [comment]
Mirrored to https://www.drupal.org/node/2899081 for credit.

Who should I credit on d.o.?

**Pull request merged**
