### PR TITLE
Remove deprecated classes

### PR DESCRIPTION
**Pull request by andypost**
Part of https://www.drupal.org/project/domain/issues/3090193

### CODE REVIEW

**Comment by andypost** [comment]
8.8 tests are broken somehow

**Comment by JTubex** [comment]
@andypost, I created #490. Tests are running again but there is still 1 test failing.

**Comment by andypost** [comment]
@JTubex Thank you, looks for 8.8 build should be fixed more

**Comment by agentrickard** [comment]
Looks good.

**Comment by agentrickard** [comment]
Moved to #497 for new testing on 8.8 and 8.9.

**Pull request merged**
